[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['cd backend && npx prisma generate']

[start]
cmd = 'cd backend && npx prisma db push --accept-data-loss && npm start'
